name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python script
        run: python Formativa1.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying...
        run: |
          echo "✅ O job de build foi um sucesso!"
          echo "🚀 Iniciando a implementação do projeto..."
          echo "🎉 Implementação finalizada!"
