name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploying to production...
        run: |
          echo "✅ O workflow de CI foi um sucesso!"
          echo "🚀 Iniciando a implementação do projeto..."
          echo "🎉 Implementação finalizada!"
